### PR TITLE
Hello, I patched my X1 Carbon 2017

### PR DESCRIPTION
**Pull request by jqqqqqqqqqq**
Thanks for your tutorial! Now my battery display is normal.

### CODE REVIEW

**Comment by RehabMan** [comment]
As per battery guide, new patches must be accompanied by native DSDT.aml.

**Comment by jqqqqqqqqqq** [comment]
Where should I put my DSDT.aml?

**Comment by RehabMan** [comment]
The guide thread is linked from the README.
That is also where new patch submissions are placed.

**Comment by jqqqqqqqqqq** [comment]
Sorry, I've posted my dsdt and patch on it. Bye!

**Pull request closed without merging**
