### PR TITLE
Create battery_Lenovo-Yoga-3-Pro.txt

### PR DESCRIPTION
**Pull request by zohaad**
[DSDT.aml.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/1715066/DSDT.aml.zip)

### CODE REVIEW

**Comment by zohaad** [comment]
[DSDT.aml.zip](https://github.com/RehabMan/Laptop-DSDT-Patch/files/1715066/DSDT.aml.zip)

**Comment by RehabMan** [comment]
Existing patch battery_Lenovo-Yoga-900-13ISK.txt looks like a match.

And your patch is wrong as it fail to properly patch access to SMD0.
(by renaming SMD0 to SMDX, but not patching the references in MHPF, you are changing the behavior of the MHPF code... causing it to reference \SMD0 instead of _SB.PCI0.LPCB.H_EC.SMD0)

**Comment by RehabMan** [comment]
If you could verify that the Yoga 900 patch works, I will commit this diff:
```
NUC6i7KYK:laptop.git rehabman$ git diff
diff --git a/battery/battery_Lenovo-Yoga-900-13ISK.txt b/battery/battery_Lenovo-Yoga-900-13ISK.txt
index 89a4b62..538a239 100644
--- a/battery/battery_Lenovo-Yoga-900-13ISK.txt
+++ b/battery/battery_Lenovo-Yoga-900-13ISK.txt
@@ -8,6 +8,7 @@
 # works for:
 #  Lenovo Yoga 900-13ISK
 #  Lenovo Miix 510-12ISK
+#  Lenovo Yoga Pro 3 (per zohaad@github)
 
 # assumes offsets as follows
 #            Field (ECF2, ByteAcc, Lock, Preserve)
```

**Comment by zohaad** [comment]
Can confirm that battery status works correctly.

0 Errors, 66 Warnings, 87 Remarks, 158 Optimizations

**Comment by RehabMan** [comment]
Comment added to battery_Lenovo-Yoga-900-13ISK.txt as mentioned above.

**Pull request closed without merging**
