### PR TITLE
[battery] patch for HP DV6-6b57er

### PR DESCRIPTION
**Pull request by urx**
This patch was tested on donovan6000 unlocked bios.

### CODE REVIEW

**Comment by RehabMan** [comment]
Read battery guide, section marked "Contributing".
I do not accept new battery patches without native DSDT for verification.
https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/

**Comment by urx** [comment]
Oh, sorry. Will be DSDT from Clover (by pressing F4) acceptable?

**Comment by RehabMan** [comment]
Yes.

**Comment by urx** [comment]
here it is - https://www.dropbox.com/s/wc3y6h3i2crlp9d/DSDT.aml?dl=0

**Comment by RehabMan** [comment]
The existing patch in the repo "HP DV6t-6b00" is a  match (not surprising).
No need for an additional patch.
I will add a comment to the file.

**Comment by urx** [comment]
Oh that's great, I didn't try it yet. 
BTW I found that BDNB length differ in two string in this patch:
into device label EC code_regex (BDNB,)\s+(56) replace_matched begin BDNBX,%2,//%1%2 end;
into method label GTBI code_regex \(\^\^PCI0\.LPCB\.EC\.BDNB, replaceall_matched begin (^^PCI0.LPCB.EC.RECB(0x08,112), end;

I am not a DSDT guru and may be this is normal and I should learn more about DSDT, but thank you anyway for these nice patches.

**Comment by RehabMan** [comment]
It is probably a mistake in the original patch.
I notice that jtp_redson did not provide an original DSDT (probably before I started asking for it)
I will look for others... from ttran001, AirAlarm...

**Comment by RehabMan** [comment]
I fixed the rename patch.  No functional change.

**Pull request closed without merging**
