### PR TITLE
battery: Add HP 2000 2d11DX

### PR DESCRIPTION
**Pull request by bhundven**
Battery for the HP 2000 2d11DX

Specifications:
http://support.hp.com/sg-en/document/c03910864

Product info:
http://support.hp.com/us-en/product/HP-2000-Notebook-PC-series/5375422/model/6412055/product-info

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

### CODE REVIEW

**Comment by RehabMan** [comment]
Please provide native DSDT.  Seems likely that you might have a match for existing patch battery_HP-Envy-17t.txt.  Or very close to where small tweaks would do the trick.  Would rather leverage an existing patch than add a completely new, almost identical patch.

**Comment by bhundven** [comment]
https://drive.google.com/file/d/0B9WMXjPtsWPWeFZaNFVENGktTGM/view?usp=sharing

**Comment by bhundven** [comment]
Btw, the audio (realtek 269vc) works with this: AppleHDA-272.18.1-ALC269VC.zip
from: http://www.insanelymac.com/forum/topic/298663-applehda-for-yosemite/
with the layout 3 patch.

**Comment by bhundven** [comment]
But audio doesn't work after sleep. But sleep doesn't work at this point so it may be because of my ssdt.

**Comment by bhundven** [comment]
Also, battery_HP-Envy-17t.txt doesn't update the methods, so I get errors due to them not getting updated.

**Comment by RehabMan** [comment]
I believe battery_HP-Envy-17t.txt can match your DSDT with only two additional patches.

Here is the diff:
```
SPEEDY-OSX:laptop.git RehabMan$ git diff
diff --git a/battery/battery_HP-Envy-17t.txt b/battery/battery_HP-Envy-17t.txt
index 08f5b81..cc64be6 100644
--- a/battery/battery_HP-Envy-17t.txt
+++ b/battery/battery_HP-Envy-17t.txt
@@ -156,6 +156,8 @@ into method label ITLB code_regex \(BFC1, replaceall_matched begin (B1B2(FC10,FC
 into method label ITLB code_regex \sBFC0, replaceall_matched begin B1B2(FC00,FC01), end;
 into method label _Q09 code_regex \(BRC0, replaceall_matched begin (B1B2(RC00,RC01), end;
 into method label _Q09 code_regex \sBFC0\) replaceall_matched begin B1B2(FC00,FC01)) end;
+into method label _Q09 code_regex \(BFC0, replaceall_matched begin (B1B2(RC00,RC01), end;
+into method label _Q09 code_regex \sBRC0\) replaceall_matched begin B1B2(FC00,FC01)) end;
 into method label GBTI code_regex \(BDV0, replaceall_matched begin (B1B2(DV00,DV01), end;
 into method label GBTI code_regex \(BDV1, replaceall_matched begin (B1B2(DV10,DV11), end;
 into method label BTIF code_regex \(BDV0, replaceall_matched begin (B1B2(DV00,DV01), end;
```

Your patch is also missing some of the patches in the Envy-17t patch (BMN0 stands out, but there are others).

Please test.

**Comment by bhundven** [comment]
@RehabMan That does work fine. Thanks! I'll get you on the forum, maybe you can advise me on getting sleep working.

**Comment by RehabMan** [comment]
Sleep is off-topic here.  Post details in the forum.

**Comment by RehabMan** [comment]
Pushed changes to the Envy-17 patch to address... Closing.

**Pull request closed without merging**
