### PR TITLE
Add ACPI battery fix for Gigabyte P34W v3 notebook

### PR DESCRIPTION
**Pull request by sztupy**
Also fixes potential issue in the u2442N file

### CODE REVIEW

**Comment by sztupy** [comment]
What do you mean by native DSDT?

I'll try to merge the two together

**Comment by sztupy** [comment]
Merged

**Comment by RehabMan** [comment]
Need native DSDT to test the patch against.

**Comment by sztupy** [comment]
Is the disassembled file as a gist okay? https://gist.github.com/sztupy/fc710e3651bbc81dd3cd

**Comment by RehabMan** [comment]
I did the pull manually in order to add some comments regarding the differences between the two different computers.

**Pull request closed without merging**
